### PR TITLE
Update to v3.4.2

### PR DESCRIPTION
**Pull request by afbora**
Updated to latest version of 3.4.2

**Phalcon Release v3.4.2:**
https://github.com/phalcon/cphalcon/releases/tag/v3.4.2

### CODE REVIEW

**Review by afbora — COMMENTED** [review]
I dont have permission to upload source file:
https://github.com/phalcon/cphalcon/archive/v3.4.2.tar.gz

**Comment by afbora** [comment]
@gitcory review the pr?

**Comment by gitcory** [comment]
Hi,

I've created case EA-8067 internally to get this in for you. I hope to have it out next week.

**Comment by afbora** [comment]
Please close the PR if completed?

**Comment by gitcory** [comment]
This has been published, sorry for not closing earlier! Thanks.

**Pull request closed without merging**
